In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
district_demo = pd.read_csv('sf1_dp_cd_demoprofile.csv')
subway_names = pd.read_csv('Stations.csv')

In [3]:
district_demo

,Table SF1-DP CD: Demographic Profile - New York City Community Districts,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2000 and 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,New York City,NaN,NaN,NaN,NaN,2000,NaN,2010,NaN,Change 2000-2010,NaN
3,NaN,NaN,NaN,NaN,NaN,Number,Percent,Number,Percent,Number,Percent
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4374,NaN,By Age of Householder:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,NaN,NaN,15 to 24 years,NaN,NaN,804,1.5,691,1.2,(113),-14.1
4376,NaN,NaN,25 to 44 years,NaN,NaN,"21,365",40.2,"17,963",31.4,"(3,402)",-15.9
4377,NaN,NaN,45 to 64 years,NaN,NaN,"21,161",39.8,"25,713",44.9,"4,552",21.5
4378,NaN,NaN,65 years and over,NaN,NaN,"9,810",18.5,"12,883",22.5,"3,073",31.3

In [4]:
data_numbers = {'Total': [], 
                'White': [], 
                'Black': [], 
                'Asian': [], 
                'Other': [], 
                'Two or more races': [], 
                'Hispanic': [], 
                'Female': [], 
                'Male': [], 
                'Under 5 years': [], 
                '5 to 9 years': [], 
                '10 to 14 years': [], 
                '15 to 19 years': [], 
                '20 to 24 years': [], 
                '25 to 44 years': [], 
                '45 to 64 years': [], 
                '65 years and over': []}
data_percentages = {'Total': [], 
                    'White': [], 
                    'Black': [], 
                    'Asian': [], 
                    'Other': [], 
                    'Two or more races': [], 
                    'Hispanic': [], 
                    'Female': [], 
                    'Male': [], 
                    'Under 5 years': [], 
                    '5 to 9 years': [], 
                    '10 to 14 years': [], 
                    '15 to 19 years': [], 
                    '20 to 24 years': [], 
                    '25 to 44 years': [], 
                    '45 to 64 years': [], 
                    '65 years and over': []}
frame_numbers = pd.DataFrame(data_numbers)
frame_percentages = pd.DataFrame(data_percentages)

In [5]:
frame_percentages

Empty DataFrame
Columns: [Total, White, Black, Asian, Other, Two or more races, Hispanic, Female, Male, Under 5 years, 5 to 9 years, 10 to 14 years, 15 to 19 years, 20 to 24 years, 25 to 44 years, 45 to 64 years, 65 years and over]
Index: []

In [6]:
district_demo.rename(columns = {'Table SF1-DP CD: Demographic Profile - New York City Community Districts': 'Districts',
                                'Unnamed: 1': 'Category', 'Unnamed: 5': '2000 Number', 'Unnamed: 6': '2000 Percent',
                                'Unnamed: 7': '2010 Number', 'Unnamed: 8': '2010 Percent', 'Unnamed: 9': 'Change Number', 
                                'Unnamed: 10': 'Change Percent'})

,Table SF1-DP CD: Demographic Profile - New York City Community Districts,Category,Unnamed: 2,Unnamed: 3,Unnamed: 4,2000 Number,2000 Percent,2010 Number,2010 Percent,Change Number,Change Percent
0,2000 and 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,New York City,NaN,NaN,NaN,NaN,2000,NaN,2010,NaN,Change 2000-2010,NaN
3,NaN,NaN,NaN,NaN,NaN,Number,Percent,Number,Percent,Number,Percent
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4374,NaN,By Age of Householder:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,NaN,NaN,15 to 24 years,NaN,NaN,804,1.5,691,1.2,(113),-14.1
4376,NaN,NaN,25 to 44 years,NaN,NaN,"21,365",40.2,"17,963",31.4,"(3,402)",-15.9
4377,NaN,NaN,45 to 64 years,NaN,NaN,"21,161",39.8,"25,713",44.9,"4,552",21.5
4378,NaN,NaN,65 years and over,NaN,NaN,"9,810",18.5,"12,883",22.5,"3,073",31.3

In [7]:
categories = ['Total', 'White', 'Black', 'Asian', 'Other', 'Two or more races', 'Hispanic', 'Female', 'Male', 
             'Under 5 years', '5 to 9 years', '10 to 14 years', '15 to 19 years', '20 to 24 years', '25 to 44 years', 
             '45 to 64 years', '65 years and over']
row_index_start = 78
dfcolumn = 0
for i in range(0, 17):
    count = 1
    column_index = 7
    numbers = []
    row_index = row_index_start
    while(count < 60):
        if(row_index <= 4378):
            numbers.append(district_demo.iloc[row_index, column_index])
            row_index = row_index + 73
            count = count + 1
    frame_numbers[categories[dfcolumn]] = numbers
    dfcolumn = dfcolumn + 1
    if row_index_start == 84 or row_index_start == 87:
        row_index_start = row_index_start + 2
    else:
        row_index_start = row_index_start + 1

row_index_start = 78
dfcolumn = 0
for i in range(0, 17):
    count = 1
    column_index = 8
    numbers = []
    row_index = row_index_start
    while(count < 60):
        if(row_index <= 4378):
            numbers.append(district_demo.iloc[row_index, column_index])
            row_index = row_index + 73
            count = count + 1
    frame_percentages[categories[dfcolumn]] = numbers
    dfcolumn = dfcolumn + 1
    if row_index_start == 84 or row_index_start == 87:
        row_index_start = row_index_start + 2
    else:
        row_index_start = row_index_start + 1

In [8]:
frame_numbers

,Total,White,Black,Asian,Other,Two or more races,Hispanic,Female,Male,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 44 years,45 to 64 years,65 years and over
0,"91,497","1,428","23,680",542,393,567,"64,887","48,615","42,882","7,609","7,572","7,462","8,910","8,135","25,332","18,343","8,134"
1,"52,246",694,"11,536",341,236,350,"39,089","27,163","25,083","4,537","4,248","4,299","4,598","4,744","15,135","10,606","4,079"
2,"79,762",918,"31,387",380,429,635,"46,013","43,395","36,367","6,842","6,733","6,874","7,709","6,773","21,608","16,846","6,377"
3,"146,441","2,193","47,344","2,258",926,"1,382","92,338","77,447","68,994","12,372","11,449","11,262","12,658","12,067","41,853","32,447","12,333"
4,"128,200","1,791","36,795","1,949",944,"1,121","85,600","67,595","60,605","10,973","10,302","10,217","11,729","11,343","36,496","28,672","8,468"
5,"83,268","6,219","21,548",952,425,675,"53,449","44,402","38,866","7,112","6,929","6,855","8,985","8,586","22,481","15,847","6,473"
6,"139,286","10,023","26,165","9,189","1,260","1,670","90,979","73,234","66,052","11,363","10,331","9,798","11,306","11,668","42,327","31,236","11,257"
7,"101,731","39,190","11,434","5,048",538,"1,365","44,156","55,831","45,900","6,315","5,332","5,260","6,696","7,262","27,386","25,534","17,946"
8,"172,298","4,749","53,070","9,937","2,559","2,632","99,351","92,207","80,091","12,422","12,266","12,602","14,345","13,383","48,891","40,677","17,712"
9,"120,392","41,554","26,713","5,529",997,"1,534","44,065","65,039","55,353","6,440","6,392","6,956","7,756","7,758","31,409","32,914","20,767"
10,"113,232","31,037","22,981","8,705","1,080","1,591","47,838","59,948","53,284","7,294","6,975","7,078","7,768","8,162","32,953","27,517","15,485"
11,"152,344","10,869","99,083","2,922","2,062","2,498","34,910","83,468","68,876","10,249","10,546","10,980","12,549","11,392","41,196","37,897","17,535"
12,"173,083","105,311","8,982","8,765",805,"2,212","47,008","87,575","85,508","14,047","11,072","9,975","10,414","16,444","66,070","30,395","14,666"
13,"99,617","45,970","27,921","7,815",610,"3,130","14,171","53,279","46,338","5,832","3,659","3,397","5,219","7,586","42,093","21,019","10,812"
14,"152,985","16,634","98,780","3,525",919,"2,639","30,488","82,524","70,461","11,315","10,463","10,480","11,639","13,663","48,912","32,994","13,519"
15,"112,634","9,564","22,688","4,807",790,"1,169","73,616","56,665","55,969","8,244","7,753","7,683","8,630","11,809","38,125","22,003","8,387"
16,"182,896","6,237","94,316","9,055","3,293","2,905","67,090","99,428","83,468","13,623","13,754","14,563","16,536","15,275","49,292","42,053","17,800"
17,"104,709","65,691","10,967","5,563",560,"2,886","19,042","55,690","49,019","7,284","5,149","4,157","3,937","5,312","45,967","23,206","9,697"
18,"126,230","29,464","3,688","33,321",612,"1,770","57,375","61,961","64,269","9,429","7,759","6,732","7,511","10,761","47,287","26,418","10,333"
19,"96,317","16,056","63,111","2,740",608,"2,304","11,498","52,890","43,427","6,233","5,373","5,492","6,030","7,753","34,190","21,747","9,499"
20,"98,429","18,825","66,958","1,239",579,"1,671","9,157","53,847","44,582","6,663","5,954","6,042","6,597","8,200","28,682","24,338","11,953"
21,"124,491","76,537","1,757","25,766",426,"2,137","17,868","64,091","60,400","7,251","6,665","6,385","6,547","7,713","39,055","32,821","18,054"
22,"181,981","90,741","1,362","62,948",530,"2,161","24,239","93,077","88,904","10,493","9,992","10,073","10,541","13,090","52,772","48,469","26,551"
23,"191,382","125,152","4,338","33,878",825,"2,335","24,854","95,273","96,109","21,724","18,334","15,975","15,308","15,143","49,276","36,708","18,914"
24,"104,278","59,405","13,401","12,310",437,"1,302","17,423","56,528","47,750","5,257","4,973","5,332","6,427","6,743","23,763","29,236","22,547"
25,"160,664","59,590","56,948","15,184","1,094","2,683","25,165","85,179","75,485","11,680","10,597","10,730","11,631","12,650","45,277","39,782","18,317"
26,"159,650","114,721","5,298","24,121",414,"2,067","13,029","83,315","76,335","9,757","9,087","8,891","9,752","11,080","40,519","44,245","26,319"
27,"86,468",858,"65,930",620,567,"1,124","17,369","48,709","37,759","6,717","6,742","7,362","8,320","7,220","22,914","19,036","8,157"
28,"155,252","2,204","137,243","1,786","1,005","2,478","10,536","86,850","68,402","9,681","9,389","9,955","11,025","11,451","42,553","42,013","19,185"
29,"193,543","50,277","115,368","7,317","1,197","3,037","16,347","106,400","87,143","11,960","12,672","13,337","14,616","13,903","50,458","53,689","22,908"
30,"60,978","40,810","2,595","10,627",319,"1,780","4,847","30,356","30,622","3,931","2,088","1,276","2,058","7,244","29,967","10,818","3,596"
31,"90,016","67,769","1,650","12,521",373,"2,110","5,593","46,391","43,625","3,059","2,203","1,670","4,450","7,381","37,891","21,556","11,806"
32,"163,277","52,898","11,294","55,180",675,"3,036","40,194","85,550","77,727","6,075","5,924","6,136","9,625","17,003","55,564","39,409","23,541"
33,"103,245","62,037","6,403","13,604",562,"2,380","18,259","49,255","53,990","3,295","2,197","1,930","2,616","8,836","46,081","26,432","11,858"
34,"51,673","34,962","2,123","9,342",204,"1,069","3,973","26,558","25,115","1,816",872,648,"1,857","6,315","23,252","11,079","5,834"
35,"142,745","103,667","4,934","19,917",601,"2,796","10,830","78,339","64,406","4,586","2,840","2,263","4,184","16,318","56,997","33,285","22,272"
36,"209,084","140,850","15,834","15,988",892,"4,173","31,347","113,169","95,915","11,460","8,155","7,028","7,218","11,636","71,965","56,915","34,707"
37,"219,920","173,711","7,098","18,945",735,"3,868","15,563","122,663","97,257","11,296","8,417","7,082","5,750","12,768","81,621","54,870","38,116"
38,"110,193","25,385","27,109","7,574",669,"2,354","47,102","58,314","51,879","5,386","4,965","5,178","9,116","15,232","35,530","22,940","11,846"
39,"115,723","11,050","72,858","2,833",718,"2,572","25,692","62,529","53,194","7,241","6,783","6,920","8,009","9,434","37,836","27,548","11,952"
40,"120,511","14,442","37,590","6,718",658,"1,813","59,290","64,227","56,284","7,229","7,038","7,432","9,301","10,747","36,865","27,199","14,700"
41,"190,020","33,442","13,954","4,814",900,"1,934","134,976","99,301","90,719","10,678","9,310","10,084","12,616","17,966","59,350","47,034","22,982"
42,"191,105","86,531","18,738","26,910","2,459","3,762","52,705","92,950","98,155","8,778","7,797","7,801","9,917","16,700","77,796","41,330","20,986"
43,"113,200","32,470","2,132","36,275",746,"2,370","39,207","55,833","57,367","6,236","5,325","4,890","5,257","8,178","44,962","26,380","11,972"
44,"171,576","20,334","10,683","27,026","1,216","2,209","110,108","82,910","88,666","11,985","10,251","9,425","10,769","14,071","58,693","39,092","17,290"
45,"172,598","12,343","9,082","57,287","1,051","2,534","90,301","84,178","88,420","11,925","10,494","9,235","10,498","14,488","59,945","39,833","16,180"
46,"169,190","92,814","2,335","13,058",705,"1,628","58,650","86,615","82,575","10,694","9,897","9,700","10,294","11,488","53,474","42,984","20,659"
47,"113,257","62,651","2,823","29,338",604,"2,405","15,436","60,653","52,604","6,145","4,877","4,179","4,387","5,659","35,505","32,065","20,440"
48,"247,354","73,668","5,512","122,094",862,"4,054","41,164","129,489","117,865","12,263","11,490","11,217","12,927","15,757","70,784","72,305","40,611"
49,"151,107","52,871","19,107","47,130","1,817","4,561","25,621","78,956","72,151","9,435","8,206","7,962","10,699","11,882","42,331","39,510","21,082"
50,"143,317","28,029","11,996","31,371","6,697","6,562","58,662","72,149","71,168","9,292","8,989","9,463","10,457","11,091","44,240","36,229","13,556"
51,"122,396","31,712","20,990","22,359","9,806","9,234","28,295","63,429","58,967","6,960","7,263","7,841","8,781","8,793","34,256","33,458","15,044"
52,"116,431","54,690","2,400","45,777",330,"1,558","11,676","60,937","55,494","5,378","5,901","6,466","6,736","6,270","30,385","35,650","19,645"
53,"225,919","3,813","147,550","20,323","7,526","7,581","39,126","121,207","104,712","14,283","14,448","15,318","17,439","17,573","62,677","57,894","26,287"
54,"188,593","24,619","104,035","27,814","4,104","5,684","22,337","101,169","87,424","10,194","10,525","11,720","13,402","13,324","49,312","53,126","26,990"
55,"114,978","40,459","44,663","2,618","1,186","1,950","24,102","60,964","54,014","8,864","8,275","8,169","8,729","7,787","29,227","28,608","15,319"
56,"175,756","69,525","38,620","13,166",931,"3,459","50,055","90,447","85,309","12,146","12,366","12,390","13,707","13,189","48,477","45,041","18,440"
57,"132,003","93,318","3,951","15,003",476,"1,827","17,428","68,699","63,304","7,226","7,471","7,885","8,513","8,400","34,142","38,481","19,885"
58,"160,209","136,851","1,667","6,653",307,"1,330","13,401","81,939","78,270","8,871","10,079","10,467","10,678","9,790","42,548","46,767","21,009"

In [9]:
frame_percentages

,Total,White,Black,Asian,Other,Two or more races,Hispanic,Female,Male,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 44 years,45 to 64 years,65 years and over
0,100.0,1.6,25.9,0.6,0.4,0.6,70.9,53.1,46.9,8.3,8.3,8.2,9.7,8.9,27.7,20.0,8.9
1,100.0,1.3,22.1,0.7,0.5,0.7,74.8,52.0,48.0,8.7,8.1,8.2,8.8,9.1,29.0,20.3,7.8
2,100.0,1.2,39.4,0.5,0.5,0.8,57.7,54.4,45.6,8.6,8.4,8.6,9.7,8.5,27.1,21.1,8.0
3,100.0,1.5,32.3,1.5,0.6,0.9,63.1,52.9,47.1,8.4,7.8,7.7,8.6,8.2,28.6,22.2,8.4
4,100.0,1.4,28.7,1.5,0.7,0.9,66.8,52.7,47.3,8.6,8.0,8.0,9.1,8.8,28.5,22.4,6.6
5,100.0,7.5,25.9,1.1,0.5,0.8,64.2,53.3,46.7,8.5,8.3,8.2,10.8,10.3,27.0,19.0,7.8
6,100.0,7.2,18.8,6.6,0.9,1.2,65.3,52.6,47.4,8.2,7.4,7.0,8.1,8.4,30.4,22.4,8.1
7,100.0,38.5,11.2,5.0,0.5,1.3,43.4,54.9,45.1,6.2,5.2,5.2,6.6,7.1,26.9,25.1,17.6
8,100.0,2.8,30.8,5.8,1.5,1.5,57.7,53.5,46.5,7.2,7.1,7.3,8.3,7.8,28.4,23.6,10.3
9,100.0,34.5,22.2,4.6,0.8,1.3,36.6,54.0,46.0,5.3,5.3,5.8,6.4,6.4,26.1,27.3,17.2
10,100.0,27.4,20.3,7.7,1.0,1.4,42.2,52.9,47.1,6.4,6.2,6.3,6.9,7.2,29.1,24.3,13.7
11,100.0,7.1,65.0,1.9,1.4,1.6,22.9,54.8,45.2,6.7,6.9,7.2,8.2,7.5,27.0,24.9,11.5
12,100.0,60.8,5.2,5.1,0.5,1.3,27.2,50.6,49.4,8.1,6.4,5.8,6.0,9.5,38.2,17.6,8.5
13,100.0,46.1,28.0,7.8,0.6,3.1,14.2,53.5,46.5,5.9,3.7,3.4,5.2,7.6,42.3,21.1,10.9
14,100.0,10.9,64.6,2.3,0.6,1.7,19.9,53.9,46.1,7.4,6.8,6.9,7.6,8.9,32.0,21.6,8.8
15,100.0,8.5,20.1,4.3,0.7,1.0,65.4,50.3,49.7,7.3,6.9,6.8,7.7,10.5,33.8,19.5,7.4
16,100.0,3.4,51.6,5.0,1.8,1.6,36.7,54.4,45.6,7.4,7.5,8.0,9.0,8.4,27.0,23.0,9.7
17,100.0,62.7,10.5,5.3,0.5,2.8,18.2,53.2,46.8,7.0,4.9,4.0,3.8,5.1,43.9,22.2,9.3
18,100.0,23.3,2.9,26.4,0.5,1.4,45.5,49.1,50.9,7.5,6.1,5.3,6.0,8.5,37.5,20.9,8.2
19,100.0,16.7,65.5,2.8,0.6,2.4,11.9,54.9,45.1,6.5,5.6,5.7,6.3,8.0,35.5,22.6,9.9
20,100.0,19.1,68.0,1.3,0.6,1.7,9.3,54.7,45.3,6.8,6.0,6.1,6.7,8.3,29.1,24.7,12.1
21,100.0,61.5,1.4,20.7,0.3,1.7,14.4,51.5,48.5,5.8,5.4,5.1,5.3,6.2,31.4,26.4,14.5
22,100.0,49.9,0.7,34.6,0.3,1.2,13.3,51.1,48.9,5.8,5.5,5.5,5.8,7.2,29.0,26.6,14.6
23,100.0,65.4,2.3,17.7,0.4,1.2,13.0,49.8,50.2,11.4,9.6,8.3,8.0,7.9,25.7,19.2,9.9
24,100.0,57.0,12.9,11.8,0.4,1.2,16.7,54.2,45.8,5.0,4.8,5.1,6.2,6.5,22.8,28.0,21.6
25,100.0,37.1,35.4,9.5,0.7,1.7,15.7,53.0,47.0,7.3,6.6,6.7,7.2,7.9,28.2,24.8,11.4
26,100.0,71.9,3.3,15.1,0.3,1.3,8.2,52.2,47.8,6.1,5.7,5.6,6.1,6.9,25.4,27.7,16.5
27,100.0,1.0,76.2,0.7,0.7,1.3,20.1,56.3,43.7,7.8,7.8,8.5,9.6,8.3,26.5,22.0,9.4
28,100.0,1.4,88.4,1.2,0.6,1.6,6.8,55.9,44.1,6.2,6.0,6.4,7.1,7.4,27.4,27.1,12.4
29,100.0,26.0,59.6,3.8,0.6,1.6,8.4,55.0,45.0,6.2,6.5,6.9,7.6,7.2,26.1,27.7,11.8
30,100.0,66.9,4.3,17.4,0.5,2.9,7.9,49.8,50.2,6.4,3.4,2.1,3.4,11.9,49.1,17.7,5.9
31,100.0,75.3,1.8,13.9,0.4,2.3,6.2,51.5,48.5,3.4,2.4,1.9,4.9,8.2,42.1,23.9,13.1
32,100.0,32.4,6.9,33.8,0.4,1.9,24.6,52.4,47.6,3.7,3.6,3.8,5.9,10.4,34.0,24.1,14.4
33,100.0,60.1,6.2,13.2,0.5,2.3,17.7,47.7,52.3,3.2,2.1,1.9,2.5,8.6,44.6,25.6,11.5
34,100.0,67.7,4.1,18.1,0.4,2.1,7.7,51.4,48.6,3.5,1.7,1.3,3.6,12.2,45.0,21.4,11.3
35,100.0,72.6,3.5,14.0,0.4,2.0,7.6,54.9,45.1,3.2,2.0,1.6,2.9,11.4,39.9,23.3,15.6
36,100.0,67.4,7.6,7.6,0.4,2.0,15.0,54.1,45.9,5.5,3.9,3.4,3.5,5.6,34.4,27.2,16.6
37,100.0,79.0,3.2,8.6,0.3,1.8,7.1,55.8,44.2,5.1,3.8,3.2,2.6,5.8,37.1,24.9,17.3
38,100.0,23.0,24.6,6.9,0.6,2.1,42.7,52.9,47.1,4.9,4.5,4.7,8.3,13.8,32.2,20.8,10.8
39,100.0,9.5,63.0,2.4,0.6,2.2,22.2,54.0,46.0,6.3,5.9,6.0,6.9,8.2,32.7,23.8,10.3
40,100.0,12.0,31.2,5.6,0.5,1.5,49.2,53.3,46.7,6.0,5.8,6.2,7.7,8.9,30.6,22.6,12.2
41,100.0,17.6,7.3,2.5,0.5,1.0,71.0,52.3,47.7,5.6,4.9,5.3,6.6,9.5,31.2,24.8,12.1
42,100.0,45.3,9.8,14.1,1.3,2.0,27.6,48.6,51.4,4.6,4.1,4.1,5.2,8.7,40.7,21.6,11.0
43,100.0,28.7,1.9,32.0,0.7,2.1,34.6,49.3,50.7,5.5,4.7,4.3,4.6,7.2,39.7,23.3,10.6
44,100.0,11.9,6.2,15.8,0.7,1.3,64.2,48.3,51.7,7.0,6.0,5.5,6.3,8.2,34.2,22.8,10.1
45,100.0,7.2,5.3,33.2,0.6,1.5,52.3,48.8,51.2,6.9,6.1,5.4,6.1,8.4,34.7,23.1,9.4
46,100.0,54.9,1.4,7.7,0.4,1.0,34.7,51.2,48.8,6.3,5.8,5.7,6.1,6.8,31.6,25.4,12.2
47,100.0,55.3,2.5,25.9,0.5,2.1,13.6,53.6,46.4,5.4,4.3,3.7,3.9,5.0,31.3,28.3,18.0
48,100.0,29.8,2.2,49.4,0.3,1.6,16.6,52.3,47.7,5.0,4.6,4.5,5.2,6.4,28.6,29.2,16.4
49,100.0,35.0,12.6,31.2,1.2,3.0,17.0,52.3,47.7,6.2,5.4,5.3,7.1,7.9,28.0,26.1,14.0
50,100.0,19.6,8.4,21.9,4.7,4.6,40.9,50.3,49.7,6.5,6.3,6.6,7.3,7.7,30.9,25.3,9.5
51,100.0,25.9,17.1,18.3,8.0,7.5,23.1,51.8,48.2,5.7,5.9,6.4,7.2,7.2,28.0,27.3,12.3
52,100.0,47.0,2.1,39.3,0.3,1.3,10.0,52.3,47.7,4.6,5.1,5.6,5.8,5.4,26.1,30.6,16.9
53,100.0,1.7,65.3,9.0,3.3,3.4,17.3,53.7,46.3,6.3,6.4,6.8,7.7,7.8,27.7,25.6,11.6
54,100.0,13.1,55.2,14.7,2.2,3.0,11.8,53.6,46.4,5.4,5.6,6.2,7.1,7.1,26.1,28.2,14.3
55,100.0,35.2,38.8,2.3,1.0,1.7,21.0,53.0,47.0,7.7,7.2,7.1,7.6,6.8,25.4,24.9,13.3
56,100.0,39.6,22.0,7.5,0.5,2.0,28.5,51.5,48.5,6.9,7.0,7.0,7.8,7.5,27.6,25.6,10.5
57,100.0,70.7,3.0,11.4,0.4,1.4,13.2,52.0,48.0,5.5,5.7,6.0,6.4,6.4,25.9,29.2,15.1
58,100.0,85.4,1.0,4.2,0.2,0.8,8.4,51.1,48.9,5.5,6.3,6.5,6.7,6.1,26.6,29.2,13.1

In [10]:
frame_numbers.index = ['Bronx_1', 'Bronx_2', 'Bronx_3', 'Bronx_4', 'Bronx_5', 'Bronx_6', 'Bronx_7', 'Bronx_8', 'Bronx_9', 'Bronx_10', 'Bronx_11', 'Bronx_12', 
                       'Brooklyn_1', 'Brooklyn_2', 'Brooklyn_3', 'Brooklyn_4', 'Brooklyn_5', 'Brooklyn_6', 'Brooklyn_7', 'Brooklyn_8', 'Brooklyn_9',
                       'Brooklyn_10', 'Brooklyn_11', 'Brooklyn_12', 'Brooklyn_13', 'Brooklyn_14', 'Brooklyn_15', 'Brooklyn_16', 'Brooklyn_17', 'Brooklyn_18',
                       'Manhattan_1', 'Manhattan_2', 'Manhattan_3', 'Manhattan_4', 'Manhattan_5', 'Manhattan_6', 'Manhattan_7', 'Manhattan_8', 'Manhattan_9', 
                       'Manhattan_10', 'Manhattan_11', 'Manhattan_12', 'Queens_1', 'Queens_2', 'Queens_3', 'Queens_4', 'Queens_5', 'Queens_6', 'Queens_7',
                       'Queens_8', 'Queens_9', 'Queens_10', 'Queens_11', 'Queens_12', 'Queens_13', 'Queens_14', 'StatenIsland_1', 'StatenIsland_2', 'StatenIsland_3']

frame_percentages.index = ['Bronx_1', 'Bronx_2', 'Bronx_3', 'Bronx_4', 'Bronx_5', 'Bronx_6', 'Bronx_7', 'Bronx_8', 'Bronx_9', 'Bronx_10', 'Bronx_11', 'Bronx_12', 
                           'Brooklyn_1', 'Brooklyn_2', 'Brooklyn_3', 'Brooklyn_4', 'Brooklyn_5', 'Brooklyn_6', 'Brooklyn_7', 'Brooklyn_8', 'Brooklyn_9',
                           'Brooklyn_10', 'Brooklyn_11', 'Brooklyn_12', 'Brooklyn_13', 'Brooklyn_14', 'Brooklyn_15', 'Brooklyn_16', 'Brooklyn_17', 'Brooklyn_18',
                           'Manhattan_1', 'Manhattan_2', 'Manhattan_3', 'Manhattan_4', 'Manhattan_5', 'Manhattan_6', 'Manhattan_7', 'Manhattan_8', 'Manhattan_9', 
                           'Manhattan_10', 'Manhattan_11', 'Manhattan_12', 'Queens_1', 'Queens_2', 'Queens_3', 'Queens_4', 'Queens_5', 'Queens_6', 'Queens_7',
                           'Queens_8', 'Queens_9', 'Queens_10', 'Queens_11', 'Queens_12', 'Queens_13', 'Queens_14', 'StatenIsland_1', 'StatenIsland_2', 'StatenIsland_3']

In [11]:
frame_numbers

,Total,White,Black,Asian,Other,Two or more races,Hispanic,Female,Male,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 44 years,45 to 64 years,65 years and over
Bronx_1,"91,497","1,428","23,680",542,393,567,"64,887","48,615","42,882","7,609","7,572","7,462","8,910","8,135","25,332","18,343","8,134"
Bronx_2,"52,246",694,"11,536",341,236,350,"39,089","27,163","25,083","4,537","4,248","4,299","4,598","4,744","15,135","10,606","4,079"
Bronx_3,"79,762",918,"31,387",380,429,635,"46,013","43,395","36,367","6,842","6,733","6,874","7,709","6,773","21,608","16,846","6,377"
Bronx_4,"146,441","2,193","47,344","2,258",926,"1,382","92,338","77,447","68,994","12,372","11,449","11,262","12,658","12,067","41,853","32,447","12,333"
Bronx_5,"128,200","1,791","36,795","1,949",944,"1,121","85,600","67,595","60,605","10,973","10,302","10,217","11,729","11,343","36,496","28,672","8,468"
Bronx_6,"83,268","6,219","21,548",952,425,675,"53,449","44,402","38,866","7,112","6,929","6,855","8,985","8,586","22,481","15,847","6,473"
Bronx_7,"139,286","10,023","26,165","9,189","1,260","1,670","90,979","73,234","66,052","11,363","10,331","9,798","11,306","11,668","42,327","31,236","11,257"
Bronx_8,"101,731","39,190","11,434","5,048",538,"1,365","44,156","55,831","45,900","6,315","5,332","5,260","6,696","7,262","27,386","25,534","17,946"
Bronx_9,"172,298","4,749","53,070","9,937","2,559","2,632","99,351","92,207","80,091","12,422","12,266","12,602","14,345","13,383","48,891","40,677","17,712"
Bronx_10,"120,392","41,554","26,713","5,529",997,"1,534","44,065","65,039","55,353","6,440","6,392","6,956","7,756","7,758","31,409","32,914","20,767"
Bronx_11,"113,232","31,037","22,981","8,705","1,080","1,591","47,838","59,948","53,284","7,294","6,975","7,078","7,768","8,162","32,953","27,517","15,485"
Bronx_12,"152,344","10,869","99,083","2,922","2,062","2,498","34,910","83,468","68,876","10,249","10,546","10,980","12,549","11,392","41,196","37,897","17,535"
Brooklyn_1,"173,083","105,311","8,982","8,765",805,"2,212","47,008","87,575","85,508","14,047","11,072","9,975","10,414","16,444","66,070","30,395","14,666"
Brooklyn_2,"99,617","45,970","27,921","7,815",610,"3,130","14,171","53,279","46,338","5,832","3,659","3,397","5,219","7,586","42,093","21,019","10,812"
Brooklyn_3,"152,985","16,634","98,780","3,525",919,"2,639","30,488","82,524","70,461","11,315","10,463","10,480","11,639","13,663","48,912","32,994","13,519"
Brooklyn_4,"112,634","9,564","22,688","4,807",790,"1,169","73,616","56,665","55,969","8,244","7,753","7,683","8,630","11,809","38,125","22,003","8,387"
Brooklyn_5,"182,896","6,237","94,316","9,055","3,293","2,905","67,090","99,428","83,468","13,623","13,754","14,563","16,536","15,275","49,292","42,053","17,800"
Brooklyn_6,"104,709","65,691","10,967","5,563",560,"2,886","19,042","55,690","49,019","7,284","5,149","4,157","3,937","5,312","45,967","23,206","9,697"
Brooklyn_7,"126,230","29,464","3,688","33,321",612,"1,770","57,375","61,961","64,269","9,429","7,759","6,732","7,511","10,761","47,287","26,418","10,333"
Brooklyn_8,"96,317","16,056","63,111","2,740",608,"2,304","11,498","52,890","43,427","6,233","5,373","5,492","6,030","7,753","34,190","21,747","9,499"
Brooklyn_9,"98,429","18,825","66,958","1,239",579,"1,671","9,157","53,847","44,582","6,663","5,954","6,042","6,597","8,200","28,682","24,338","11,953"
Brooklyn_10,"124,491","76,537","1,757","25,766",426,"2,137","17,868","64,091","60,400","7,251","6,665","6,385","6,547","7,713","39,055","32,821","18,054"
Brooklyn_11,"181,981","90,741","1,362","62,948",530,"2,161","24,239","93,077","88,904","10,493","9,992","10,073","10,541","13,090","52,772","48,469","26,551"
Brooklyn_12,"191,382","125,152","4,338","33,878",825,"2,335","24,854","95,273","96,109","21,724","18,334","15,975","15,308","15,143","49,276","36,708","18,914"
Brooklyn_13,"104,278","59,405","13,401","12,310",437,"1,302","17,423","56,528","47,750","5,257","4,973","5,332","6,427","6,743","23,763","29,236","22,547"
Brooklyn_14,"160,664","59,590","56,948","15,184","1,094","2,683","25,165","85,179","75,485","11,680","10,597","10,730","11,631","12,650","45,277","39,782","18,317"
Brooklyn_15,"159,650","114,721","5,298","24,121",414,"2,067","13,029","83,315","76,335","9,757","9,087","8,891","9,752","11,080","40,519","44,245","26,319"
Brooklyn_16,"86,468",858,"65,930",620,567,"1,124","17,369","48,709","37,759","6,717","6,742","7,362","8,320","7,220","22,914","19,036","8,157"
Brooklyn_17,"155,252","2,204","137,243","1,786","1,005","2,478","10,536","86,850","68,402","9,681","9,389","9,955","11,025","11,451","42,553","42,013","19,185"
Brooklyn_18,"193,543","50,277","115,368","7,317","1,197","3,037","16,347","106,400","87,143","11,960","12,672","13,337","14,616","13,903","50,458","53,689","22,908"
Manhattan_1,"60,978","40,810","2,595","10,627",319,"1,780","4,847","30,356","30,622","3,931","2,088","1,276","2,058","7,244","29,967","10,818","3,596"
Manhattan_2,"90,016","67,769","1,650","12,521",373,"2,110","5,593","46,391","43,625","3,059","2,203","1,670","4,450","7,381","37,891","21,556","11,806"
Manhattan_3,"163,277","52,898","11,294","55,180",675,"3,036","40,194","85,550","77,727","6,075","5,924","6,136","9,625","17,003","55,564","39,409","23,541"
Manhattan_4,"103,245","62,037","6,403","13,604",562,"2,380","18,259","49,255","53,990","3,295","2,197","1,930","2,616","8,836","46,081","26,432","11,858"
Manhattan_5,"51,673","34,962","2,123","9,342",204,"1,069","3,973","26,558","25,115","1,816",872,648,"1,857","6,315","23,252","11,079","5,834"
Manhattan_6,"142,745","103,667","4,934","19,917",601,"2,796","10,830","78,339","64,406","4,586","2,840","2,263","4,184","16,318","56,997","33,285","22,272"
Manhattan_7,"209,084","140,850","15,834","15,988",892,"4,173","31,347","113,169","95,915","11,460","8,155","7,028","7,218","11,636","71,965","56,915","34,707"
Manhattan_8,"219,920","173,711","7,098","18,945",735,"3,868","15,563","122,663","97,257","11,296","8,417","7,082","5,750","12,768","81,621","54,870","38,116"
Manhattan_9,"110,193","25,385","27,109","7,574",669,"2,354","47,102","58,314","51,879","5,386","4,965","5,178","9,116","15,232","35,530","22,940","11,846"
Manhattan_10,"115,723","11,050","72,858","2,833",718,"2,572","25,692","62,529","53,194","7,241","6,783","6,920","8,009","9,434","37,836","27,548","11,952"
Manhattan_11,"120,511","14,442","37,590","6,718",658,"1,813","59,290","64,227","56,284","7,229","7,038","7,432","9,301","10,747","36,865","27,199","14,700"
Manhattan_12,"190,020","33,442","13,954","4,814",900,"1,934","134,976","99,301","90,719","10,678","9,310","10,084","12,616","17,966","59,350","47,034","22,982"
Queens_1,"191,105","86,531","18,738","26,910","2,459","3,762","52,705","92,950","98,155","8,778","7,797","7,801","9,917","16,700","77,796","41,330","20,986"
Queens_2,"113,200","32,470","2,132","36,275",746,"2,370","39,207","55,833","57,367","6,236","5,325","4,890","5,257","8,178","44,962","26,380","11,972"
Queens_3,"171,576","20,334","10,683","27,026","1,216","2,209","110,108","82,910","88,666","11,985","10,251","9,425","10,769","14,071","58,693","39,092","17,290"
Queens_4,"172,598","12,343","9,082","57,287","1,051","2,534","90,301","84,178","88,420","11,925","10,494","9,235","10,498","14,488","59,945","39,833","16,180"
Queens_5,"169,190","92,814","2,335","13,058",705,"1,628","58,650","86,615","82,575","10,694","9,897","9,700","10,294","11,488","53,474","42,984","20,659"
Queens_6,"113,257","62,651","2,823","29,338",604,"2,405","15,436","60,653","52,604","6,145","4,877","4,179","4,387","5,659","35,505","32,065","20,440"
Queens_7,"247,354","73,668","5,512","122,094",862,"4,054","41,164","129,489","117,865","12,263","11,490","11,217","12,927","15,757","70,784","72,305","40,611"
Queens_8,"151,107","52,871","19,107","47,130","1,817","4,561","25,621","78,956","72,151","9,435","8,206","7,962","10,699","11,882","42,331","39,510","21,082"
Queens_9,"143,317","28,029","11,996","31,371","6,697","6,562","58,662","72,149","71,168","9,292","8,989","9,463","10,457","11,091","44,240","36,229","13,556"
Queens_10,"122,396","31,712","20,990","22,359","9,806","9,234","28,295","63,429","58,967","6,960","7,263","7,841","8,781","8,793","34,256","33,458","15,044"
Queens_11,"116,431","54,690","2,400","45,777",330,"1,558","11,676","60,937","55,494","5,378","5,901","6,466","6,736","6,270","30,385","35,650","19,645"
Queens_12,"225,919","3,813","147,550","20,323","7,526","7,581","39,126","121,207","104,712","14,283","14,448","15,318","17,439","17,573","62,677","57,894","26,287"
Queens_13,"188,593","24,619","104,035","27,814","4,104","5,684","22,337","101,169","87,424","10,194","10,525","11,720","13,402","13,324","49,312","53,126","26,990"
Queens_14,"114,978","40,459","44,663","2,618","1,186","1,950","24,102","60,964","54,014","8,864","8,275","8,169","8,729","7,787","29,227","28,608","15,319"
StatenIsland_1,"175,756","69,525","38,620","13,166",931,"3,459","50,055","90,447","85,309","12,146","12,366","12,390","13,707","13,189","48,477","45,041","18,440"
StatenIsland_2,"132,003","93,318","3,951","15,003",476,"1,827","17,428","68,699","63,304","7,226","7,471","7,885","8,513","8,400","34,142","38,481","19,885"
StatenIsland_3,"160,209","136,851","1,667","6,653",307,"1,330","13,401","81,939","78,270","8,871","10,079","10,467","10,678","9,790","42,548","46,767","21,009"

In [12]:
frame_percentages

,Total,White,Black,Asian,Other,Two or more races,Hispanic,Female,Male,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 44 years,45 to 64 years,65 years and over
Bronx_1,100.0,1.6,25.9,0.6,0.4,0.6,70.9,53.1,46.9,8.3,8.3,8.2,9.7,8.9,27.7,20.0,8.9
Bronx_2,100.0,1.3,22.1,0.7,0.5,0.7,74.8,52.0,48.0,8.7,8.1,8.2,8.8,9.1,29.0,20.3,7.8
Bronx_3,100.0,1.2,39.4,0.5,0.5,0.8,57.7,54.4,45.6,8.6,8.4,8.6,9.7,8.5,27.1,21.1,8.0
Bronx_4,100.0,1.5,32.3,1.5,0.6,0.9,63.1,52.9,47.1,8.4,7.8,7.7,8.6,8.2,28.6,22.2,8.4
Bronx_5,100.0,1.4,28.7,1.5,0.7,0.9,66.8,52.7,47.3,8.6,8.0,8.0,9.1,8.8,28.5,22.4,6.6
Bronx_6,100.0,7.5,25.9,1.1,0.5,0.8,64.2,53.3,46.7,8.5,8.3,8.2,10.8,10.3,27.0,19.0,7.8
Bronx_7,100.0,7.2,18.8,6.6,0.9,1.2,65.3,52.6,47.4,8.2,7.4,7.0,8.1,8.4,30.4,22.4,8.1
Bronx_8,100.0,38.5,11.2,5.0,0.5,1.3,43.4,54.9,45.1,6.2,5.2,5.2,6.6,7.1,26.9,25.1,17.6
Bronx_9,100.0,2.8,30.8,5.8,1.5,1.5,57.7,53.5,46.5,7.2,7.1,7.3,8.3,7.8,28.4,23.6,10.3
Bronx_10,100.0,34.5,22.2,4.6,0.8,1.3,36.6,54.0,46.0,5.3,5.3,5.8,6.4,6.4,26.1,27.3,17.2
Bronx_11,100.0,27.4,20.3,7.7,1.0,1.4,42.2,52.9,47.1,6.4,6.2,6.3,6.9,7.2,29.1,24.3,13.7
Bronx_12,100.0,7.1,65.0,1.9,1.4,1.6,22.9,54.8,45.2,6.7,6.9,7.2,8.2,7.5,27.0,24.9,11.5
Brooklyn_1,100.0,60.8,5.2,5.1,0.5,1.3,27.2,50.6,49.4,8.1,6.4,5.8,6.0,9.5,38.2,17.6,8.5
Brooklyn_2,100.0,46.1,28.0,7.8,0.6,3.1,14.2,53.5,46.5,5.9,3.7,3.4,5.2,7.6,42.3,21.1,10.9
Brooklyn_3,100.0,10.9,64.6,2.3,0.6,1.7,19.9,53.9,46.1,7.4,6.8,6.9,7.6,8.9,32.0,21.6,8.8
Brooklyn_4,100.0,8.5,20.1,4.3,0.7,1.0,65.4,50.3,49.7,7.3,6.9,6.8,7.7,10.5,33.8,19.5,7.4
Brooklyn_5,100.0,3.4,51.6,5.0,1.8,1.6,36.7,54.4,45.6,7.4,7.5,8.0,9.0,8.4,27.0,23.0,9.7
Brooklyn_6,100.0,62.7,10.5,5.3,0.5,2.8,18.2,53.2,46.8,7.0,4.9,4.0,3.8,5.1,43.9,22.2,9.3
Brooklyn_7,100.0,23.3,2.9,26.4,0.5,1.4,45.5,49.1,50.9,7.5,6.1,5.3,6.0,8.5,37.5,20.9,8.2
Brooklyn_8,100.0,16.7,65.5,2.8,0.6,2.4,11.9,54.9,45.1,6.5,5.6,5.7,6.3,8.0,35.5,22.6,9.9
Brooklyn_9,100.0,19.1,68.0,1.3,0.6,1.7,9.3,54.7,45.3,6.8,6.0,6.1,6.7,8.3,29.1,24.7,12.1
Brooklyn_10,100.0,61.5,1.4,20.7,0.3,1.7,14.4,51.5,48.5,5.8,5.4,5.1,5.3,6.2,31.4,26.4,14.5
Brooklyn_11,100.0,49.9,0.7,34.6,0.3,1.2,13.3,51.1,48.9,5.8,5.5,5.5,5.8,7.2,29.0,26.6,14.6
Brooklyn_12,100.0,65.4,2.3,17.7,0.4,1.2,13.0,49.8,50.2,11.4,9.6,8.3,8.0,7.9,25.7,19.2,9.9
Brooklyn_13,100.0,57.0,12.9,11.8,0.4,1.2,16.7,54.2,45.8,5.0,4.8,5.1,6.2,6.5,22.8,28.0,21.6
Brooklyn_14,100.0,37.1,35.4,9.5,0.7,1.7,15.7,53.0,47.0,7.3,6.6,6.7,7.2,7.9,28.2,24.8,11.4
Brooklyn_15,100.0,71.9,3.3,15.1,0.3,1.3,8.2,52.2,47.8,6.1,5.7,5.6,6.1,6.9,25.4,27.7,16.5
Brooklyn_16,100.0,1.0,76.2,0.7,0.7,1.3,20.1,56.3,43.7,7.8,7.8,8.5,9.6,8.3,26.5,22.0,9.4
Brooklyn_17,100.0,1.4,88.4,1.2,0.6,1.6,6.8,55.9,44.1,6.2,6.0,6.4,7.1,7.4,27.4,27.1,12.4
Brooklyn_18,100.0,26.0,59.6,3.8,0.6,1.6,8.4,55.0,45.0,6.2,6.5,6.9,7.6,7.2,26.1,27.7,11.8
Manhattan_1,100.0,66.9,4.3,17.4,0.5,2.9,7.9,49.8,50.2,6.4,3.4,2.1,3.4,11.9,49.1,17.7,5.9
Manhattan_2,100.0,75.3,1.8,13.9,0.4,2.3,6.2,51.5,48.5,3.4,2.4,1.9,4.9,8.2,42.1,23.9,13.1
Manhattan_3,100.0,32.4,6.9,33.8,0.4,1.9,24.6,52.4,47.6,3.7,3.6,3.8,5.9,10.4,34.0,24.1,14.4
Manhattan_4,100.0,60.1,6.2,13.2,0.5,2.3,17.7,47.7,52.3,3.2,2.1,1.9,2.5,8.6,44.6,25.6,11.5
Manhattan_5,100.0,67.7,4.1,18.1,0.4,2.1,7.7,51.4,48.6,3.5,1.7,1.3,3.6,12.2,45.0,21.4,11.3
Manhattan_6,100.0,72.6,3.5,14.0,0.4,2.0,7.6,54.9,45.1,3.2,2.0,1.6,2.9,11.4,39.9,23.3,15.6
Manhattan_7,100.0,67.4,7.6,7.6,0.4,2.0,15.0,54.1,45.9,5.5,3.9,3.4,3.5,5.6,34.4,27.2,16.6
Manhattan_8,100.0,79.0,3.2,8.6,0.3,1.8,7.1,55.8,44.2,5.1,3.8,3.2,2.6,5.8,37.1,24.9,17.3
Manhattan_9,100.0,23.0,24.6,6.9,0.6,2.1,42.7,52.9,47.1,4.9,4.5,4.7,8.3,13.8,32.2,20.8,10.8
Manhattan_10,100.0,9.5,63.0,2.4,0.6,2.2,22.2,54.0,46.0,6.3,5.9,6.0,6.9,8.2,32.7,23.8,10.3
Manhattan_11,100.0,12.0,31.2,5.6,0.5,1.5,49.2,53.3,46.7,6.0,5.8,6.2,7.7,8.9,30.6,22.6,12.2
Manhattan_12,100.0,17.6,7.3,2.5,0.5,1.0,71.0,52.3,47.7,5.6,4.9,5.3,6.6,9.5,31.2,24.8,12.1
Queens_1,100.0,45.3,9.8,14.1,1.3,2.0,27.6,48.6,51.4,4.6,4.1,4.1,5.2,8.7,40.7,21.6,11.0
Queens_2,100.0,28.7,1.9,32.0,0.7,2.1,34.6,49.3,50.7,5.5,4.7,4.3,4.6,7.2,39.7,23.3,10.6
Queens_3,100.0,11.9,6.2,15.8,0.7,1.3,64.2,48.3,51.7,7.0,6.0,5.5,6.3,8.2,34.2,22.8,10.1
Queens_4,100.0,7.2,5.3,33.2,0.6,1.5,52.3,48.8,51.2,6.9,6.1,5.4,6.1,8.4,34.7,23.1,9.4
Queens_5,100.0,54.9,1.4,7.7,0.4,1.0,34.7,51.2,48.8,6.3,5.8,5.7,6.1,6.8,31.6,25.4,12.2
Queens_6,100.0,55.3,2.5,25.9,0.5,2.1,13.6,53.6,46.4,5.4,4.3,3.7,3.9,5.0,31.3,28.3,18.0
Queens_7,100.0,29.8,2.2,49.4,0.3,1.6,16.6,52.3,47.7,5.0,4.6,4.5,5.2,6.4,28.6,29.2,16.4
Queens_8,100.0,35.0,12.6,31.2,1.2,3.0,17.0,52.3,47.7,6.2,5.4,5.3,7.1,7.9,28.0,26.1,14.0
Queens_9,100.0,19.6,8.4,21.9,4.7,4.6,40.9,50.3,49.7,6.5,6.3,6.6,7.3,7.7,30.9,25.3,9.5
Queens_10,100.0,25.9,17.1,18.3,8.0,7.5,23.1,51.8,48.2,5.7,5.9,6.4,7.2,7.2,28.0,27.3,12.3
Queens_11,100.0,47.0,2.1,39.3,0.3,1.3,10.0,52.3,47.7,4.6,5.1,5.6,5.8,5.4,26.1,30.6,16.9
Queens_12,100.0,1.7,65.3,9.0,3.3,3.4,17.3,53.7,46.3,6.3,6.4,6.8,7.7,7.8,27.7,25.6,11.6
Queens_13,100.0,13.1,55.2,14.7,2.2,3.0,11.8,53.6,46.4,5.4,5.6,6.2,7.1,7.1,26.1,28.2,14.3
Queens_14,100.0,35.2,38.8,2.3,1.0,1.7,21.0,53.0,47.0,7.7,7.2,7.1,7.6,6.8,25.4,24.9,13.3
StatenIsland_1,100.0,39.6,22.0,7.5,0.5,2.0,28.5,51.5,48.5,6.9,7.0,7.0,7.8,7.5,27.6,25.6,10.5
StatenIsland_2,100.0,70.7,3.0,11.4,0.4,1.4,13.2,52.0,48.0,5.5,5.7,6.0,6.4,6.4,25.9,29.2,15.1
StatenIsland_3,100.0,85.4,1.0,4.2,0.2,0.8,8.4,51.1,48.9,5.5,6.3,6.5,6.7,6.1,26.6,29.2,13.1